### ISSUE TITLE
Build in Xcode

### ISSUE THREAD

**Issue by MihaelIsaev** [Longhanks/qlift-swift-example#3]
Hello!

I've successfully wrapped `qlift-c-api` using `modulemap`, but I can't find a way how to import 
```
/usr/local/opt/qt/lib/QtCore.framework/QtCore
/usr/local/opt/qt/lib/QtGui.framework/QtGui
/usr/local/opt/qt/lib/QtWidgets.framework/QtWidgets
```
and also how to pass 
```
-Xlinker -search_paths_first
-Xlinker -lc++
```
into SwiftPM's `Package.swift`

Could you please help with proper `Package.swift` to be able to build demo app via Xcode?
It'd be great from my point of view 🙂 

Thank you in advance!

**Comment by Longhanks** [comment]
Xcode is currently not supported, because building is only possible with buildscript.sh, as the build requires a call to the `qlift-uic` binary (compiling *.ui files).

**Comment by Longhanks** [comment]
Xcode is now supported.
